# This is the default config file for PlayerBridge.
# This config was generated for version ${version}.

# Configure database constants.
database:
  host: "127.0.0.1"
  port: 3306
  database: "player_bridge"
  username: "root"
  password: ""
  # HikariCP configuration constants. If you do not know what these do, just ignore them.
  max-pool-size: 10
  min-pool-size: 2
  connection-timeout-ms: 5000

# Ownership mechanism to prevent race-conditions. Defaults should be fine in most cases.
ownership:
  lease-duration-seconds: 60

# Handles player-data saving and loading. Defaults should be fine as well.
player-data:
  login-timeout-seconds: 5
  retry-interval-ms: 250
  final-save-timeout-seconds: 15

# Fully configurable messages supporting minecraft color constants and hex colors.
# https://docs.papermc.io/adventure/minimessage/format/
messages:
  no-permission: "<red>You do not have permission to use this command.</red>"
  reload-config: "<green>Configuration successfully reloaded.</green>"
  check-version: "<gray>You are running version <white><version></white> (<white><server_version></white>).</gray>"